[package]

name = "hyper"
version = "0.3.5"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper/hyper/index.html"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]

[dependencies]
cookie = "*"
httparse = "*"
log = ">= 0.2.0"
mime = "*"
num_cpus = "*"
openssl = "*"
rustc-serialize = "*"
time = "*"
unicase = "*"
url = "*"

[dev-dependencies]
env_logger = "*"

