[package]
name = "hyper"
version = "0.13.0-alpha.1" # don't forget to update html_root_url
description = "A fast and correct HTTP library."
readme = "README.md"
homepage = "https://hyper.rs"
documentation = "https://docs.rs/hyper"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
keywords = ["http", "hyper", "hyperium"]
categories = ["network-programming", "web-programming::http-client", "web-programming::http-server"]
edition = "2018"

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*",
  #"build.rs",
]

[dependencies]
bytes = "0.4.4"
futures-core-preview = { version = "=0.3.0-alpha.18" }
futures-channel-preview = { version = "=0.3.0-alpha.18" }
futures-util-preview = { version = "=0.3.0-alpha.18" }
http = "0.1.15"
http-body = "=0.2.0-alpha.1"
httparse = "1.0"
h2 = "=0.2.0-alpha.1"
iovec = "0.1"
itoa = "0.4.1"
log = "0.4"
net2 = { version = "0.2.32", optional = true }
pin-project = { version = "=0.4.0-alpha.9", features = ["project_attr"] }
time = "0.1"
tokio = { version = "=0.2.0-alpha.4", optional = true, default-features = false, features = ["rt-full"] }
tower-service = "=0.3.0-alpha.1"
tower-make = { version = "=0.1.0-alpha.2", features = ['io'] }
tokio-executor = { version = "=0.2.0-alpha.4", features = ["blocking"] }
tokio-io = "=0.2.0-alpha.4"
tokio-sync = "=0.2.0-alpha.4"
tokio-net = { version = "=0.2.0-alpha.4", optional = true, features = ["tcp"] }
tokio-timer = { version = "=0.3.0-alpha.4", optional = true }
want = "0.3"

[dev-dependencies]
matches = "0.1"
num_cpus = "1.0"
pretty_env_logger = "0.3"
spmc = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "=0.2.0-alpha.4" # using #[tokio::test] attributes
tokio-fs = "=0.2.0-alpha.4"
tokio-test = "=0.2.0-alpha.4"
url = "1.0"


[features]
default = [
    "__internal_flaky_tests",
    "runtime",
]
runtime = [
    "net2",
    "tokio",
    "tokio-net",
    "tokio-timer",
]

# unstable features
stream = []

# internal features used in CI
nightly = []
__internal_flaky_tests = []
__internal_happy_eyeballs_tests = []

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["runtime"]

[[example]]
name = "client_json"
path = "examples/client_json.rs"
required-features = ["runtime"]

[[example]]
name = "echo"
path = "examples/echo.rs"
required-features = ["runtime"]

[[example]]
name = "hello"
path = "examples/hello.rs"
required-features = ["runtime"]

[[example]]
name = "multi_server"
path = "examples/multi_server.rs"
required-features = ["runtime"]

[[example]]
name = "params"
path = "examples/params.rs"
required-features = ["runtime"]

[[example]]
name = "proxy"
path = "examples/proxy.rs"
required-features = ["runtime"]

[[example]]
name = "send_file"
path = "examples/send_file.rs"
required-features = ["runtime"]

[[example]]
name = "single_threaded"
path = "examples/single_threaded.rs"
required-features = ["runtime"]

[[example]]
name = "state"
path = "examples/state.rs"
required-features = ["runtime"]

[[example]]
name = "tower_client"
path = "examples/tower_client.rs"
required-features = ["runtime"]

[[example]]
name = "tower_server"
path = "examples/tower_server.rs"
required-features = ["runtime"]

[[example]]
name = "upgrades"
path = "examples/upgrades.rs"
required-features = ["runtime"]


[[example]]
name = "web_api"
path = "examples/web_api.rs"
required-features = ["runtime"]


[[bench]]
name = "end_to_end"
path = "benches/end_to_end.rs"
required-features = ["runtime"]

[[bench]]
name = "pipeline"
path = "benches/pipeline.rs"
required-features = ["runtime"]

[[bench]]
name = "server"
path = "benches/server.rs"
required-features = ["runtime"]


[[test]]
name = "client"
path = "tests/client.rs"
required-features = ["runtime"]

[[test]]
name = "integration"
path = "tests/integration.rs"
required-features = ["runtime"]

[[test]]
name = "server"
path = "tests/server.rs"
required-features = ["runtime"]
