[package]

name = "hyper"
version = "0.5.1"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper/hyper/index.html"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]

[dependencies]
cookie = "0.1"
httparse = "0.1"
log = "0.3"
mime = "0.0.11"
num_cpus = "0.2"
openssl = "0.6"
rustc-serialize = "0.3"
time = "0.1"
unicase = "0.1"
url = "0.2"
traitobject = "0.0.1"
typeable = "0.1"

[dev-dependencies]
env_logger = "*"

[features]
nightly = []
