[package]

name = "hyper"
version = "0.0.21"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper/hyper/index.html"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]

[dependencies]
url = "*"
openssl = "*"
mime = "*"
unsafe-any = "*"
cookie = "*"
time = "*"
mucell = "*"
log = "*"
rustc-serialize = "*"

[dev-dependencies]
curl = "*"

